"""Sidebar, footer y branding por sitio para /docs/, extraido
2026-07-27 -- ver docs_gen.py. Un solo sidebar/footer por sitio
(identico en las paginas de ese sitio salvo el link activo del
sidebar, confirmado en la extraccion)."""

SIDEBARS = {
    # 🔴 Sidebar re-extraido de lo desplegado el 2026-08-21, junto con las 21
    # paginas. El que habia aca era el de 15 paginas y ya no coincidia con el
    # del sitio: le faltaban las 6 nuevas y tenia otra reparticion en secciones
    # ("Clientes y equipos" e "Inventario y compras" en vez de "Inventario" y
    # "Comprobantes"). Ver la nota de `docs_pages.py`.
    'libradesk': {

        "brand": 'LibraDesk',
        "letter": 'L',
        "footer_html": '<footer style="background:var(--dark);color:#94a3b8;text-align:center;padding:1.5rem;font-size:.85rem;">\n  © 2026 LibraDesk · <a href="/" style="color:#94a3b8">Inicio</a>\n</footer>',
        "sidebar": [
            {"type": "section", "text": 'Inicio'},
            {"type": "link", "href": '/docs/', "text": 'Introducción'},
            {"type": "link", "href": '/docs/primeros-pasos.html', "text": 'Primeros pasos'},
            {"type": "link", "href": '/docs/recorrido.html', "text": 'El recorrido completo'},
            {"type": "section", "text": 'Día a día'},
            {"type": "link", "href": '/docs/dashboard.html', "text": 'Dashboard'},
            {"type": "link", "href": '/docs/agenda.html', "text": 'Agenda'},
            {"type": "link", "href": '/docs/incidencias.html', "text": 'Incidencias'},
            {"type": "link", "href": '/docs/recepcion-reparaciones.html', "text": 'Recepción y reparaciones'},
            {"type": "section", "text": 'Clientes y equipos'},
            {"type": "link", "href": '/docs/clientes.html', "text": 'Clientes'},
            {"type": "link", "href": '/docs/equipos.html', "text": 'Equipos'},
            {"type": "link", "href": '/docs/depositos.html', "text": 'Depósitos'},
            {"type": "link", "href": '/docs/equipos-flota.html', "text": 'Equipos y flota'},
            {"type": "section", "text": 'Inventario y compras'},
            {"type": "link", "href": '/docs/stock.html', "text": 'Stock y productos'},
            {"type": "link", "href": '/docs/compras.html', "text": 'Compras'},
            {"type": "section", "text": 'Ventas'},
            {"type": "link", "href": '/docs/presupuestos-remitos.html', "text": 'Presupuestos y remitos'},
            {"type": "link", "href": '/docs/ventas-cobranzas.html', "text": 'Ventas y cobranzas'},
            {"type": "link", "href": '/docs/facturacion.html', "text": 'Enviar a facturar'},
            {"type": "section", "text": 'Alquileres'},
            {"type": "link", "href": '/docs/contratos.html', "text": 'Equipos en alquiler'},
            {"type": "link", "href": '/docs/activos.html', "text": 'Activos'},
            {"type": "section", "text": 'Administración'},
            {"type": "link", "href": '/docs/reportes.html', "text": 'Reportes'},
            {"type": "link", "href": '/docs/configuracion.html', "text": 'Configuración'},
            {"type": "link", "href": '/docs/usuarios-logs.html', "text": 'Usuarios y logs'},
        ],
    },
    'contalibra': {
        "brand": 'Contalibra',
        "letter": 'C',
        "footer_html": '<footer style="background:var(--dark);color:#94a3b8;text-align:center;padding:1.5rem;font-size:.85rem;">\n  © 2026 Contalibra · <a href="/" style="color:#94a3b8">Inicio</a>\n</footer>',
        "sidebar": [
            {"type": "section", "text": 'Inicio'},
            {"type": "link", "href": '/docs/', "text": 'Introducción'},
            {"type": "link", "href": '/docs/primeros-pasos.html', "text": 'Primeros pasos'},
            {"type": "section", "text": 'Configuración'},
            {"type": "link", "href": '/docs/empresa.html', "text": 'Datos de la empresa'},
            {"type": "link", "href": '/docs/usuarios.html', "text": 'Usuarios y permisos'},
            {"type": "link", "href": '/docs/configuracion.html', "text": 'Configuración general'},
            {"type": "section", "text": 'Módulos'},
            {"type": "link", "href": '/docs/ventas.html', "text": 'Ventas'},
            {"type": "link", "href": '/docs/presupuestos.html', "text": 'Presupuestos'},
            {"type": "link", "href": '/docs/clientes.html', "text": 'Clientes'},
            {"type": "link", "href": '/docs/cuenta-corriente.html', "text": 'Cuenta Corriente'},
            {"type": "link", "href": '/docs/caja-turnos.html', "text": 'Caja y Turnos'},
            {"type": "link", "href": '/docs/facturacion.html', "text": 'Facturación electrónica'},
            {"type": "link", "href": '/docs/productos-stock.html', "text": 'Productos y Stock'},
            {"type": "link", "href": '/docs/listas-precio.html', "text": 'Listas de Precios'},
            {"type": "link", "href": '/docs/egresos-proveedores.html', "text": 'Egresos y Proveedores'},
            {"type": "link", "href": '/docs/tesoreria.html', "text": 'Tesorería'},
            {"type": "link", "href": '/docs/depositos.html', "text": 'Depósitos'},
            {"type": "link", "href": '/docs/reportes.html', "text": 'Reportes'},
            {"type": "link", "href": '/docs/libros-iva.html', "text": 'Libros IVA Digital'},
            {"type": "link", "href": '/docs/integraciones.html', "text": 'Integraciones'},
            {"type": "link", "href": '/docs/logs.html', "text": 'Logs de actividad'},
        ],
    },
    'restolibra': {
        "brand": 'Restolibra',
        "letter": 'R',
        "footer_html": '<footer>\n<div class="footer-inner">\n<div>\n<div class="footer-brand">\n<div class="logo-icon" style="width:28px;height:28px;border-radius:6px;background:var(--brand);display:inline-flex;align-items:center;justify-content:center;color:white;font-weight:900;font-size:.8rem">R</div>\n        Restolibra\n      </div>\n<div class="footer-tagline">Sistema de gestión para restaurantes, bares y delivery</div>\n</div>\n<div style="display:flex;gap:3rem;flex-wrap:wrap">\n<div>\n<div style="font-size:.8rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#78716c;margin-bottom:.75rem">Sistema</div>\n<div style="display:flex;flex-direction:column;gap:.4rem">\n<a href="/#funciones" style="color:#a8a29e;font-size:.9rem">Funciones</a>\n<a href="/#planes" style="color:#a8a29e;font-size:.9rem">Planes</a>\n</div>\n</div>\n<div>\n<div style="font-size:.8rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#78716c;margin-bottom:.75rem">Recursos</div>\n<div style="display:flex;flex-direction:column;gap:.4rem">\n<a href="/docs/" style="color:#a8a29e;font-size:.9rem">Documentación</a>\n<a href="/docs/primeros-pasos.html" style="color:#a8a29e;font-size:.9rem">Primeros pasos</a>\n<a href="/docs/salon.html" style="color:#a8a29e;font-size:.9rem">Salón y Mesas</a>\n</div>\n</div>\n<div>\n<div style="font-size:.8rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#78716c;margin-bottom:.75rem">Contacto</div>\n<div style="display:flex;flex-direction:column;gap:.4rem">\n<a href="https://wa.me/5491127752983" style="color:#a8a29e;font-size:.9rem" target="_blank"><i class="bi bi-whatsapp me-1"></i>WhatsApp</a>\n<a href="mailto:hola@restolibra.com.ar" style="color:#a8a29e;font-size:.9rem"><i class="bi bi-envelope me-1"></i>Email</a>\n</div>\n</div>\n<div>\n<div style="font-size:.8rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#78716c;margin-bottom:.75rem">Nuestro Ecosistema</div>\n<div style="display:flex;flex-direction:column;gap:.4rem">\n<a href="https://contalibra.com.ar" rel="noopener" style="color:#a8a29e;font-size:.9rem" target="_blank">Contalibra — ERP &amp; Facturación</a>\n<a href="https://compulibra.com.ar" rel="noopener" style="color:#a8a29e;font-size:.9rem" target="_blank">Compulibra — Soporte IT &amp; Hosting</a>\n<a href="https://neuroflow.com.ar" rel="noopener" style="color:#a8a29e;font-size:.9rem" target="_blank">NeuroFlow — IA &amp; Automatización</a>\n</div>\n</div>\n</div>\n</div>\n<div class="footer-copy">\n    © 2026 Restolibra · parte del ecosistema <a href="https://compulibra.com.ar" rel="noopener" style="color:#78716c;text-decoration:none" target="_blank">Compulibra</a> · Todos los derechos reservados\n  </div>\n</footer>',
        "sidebar": [
            {"type": "section", "text": 'Inicio'},
            {"type": "link", "href": '/docs/', "text": 'Introducción'},
            {"type": "link", "href": '/docs/primeros-pasos.html', "text": 'Primeros pasos'},
            {"type": "section", "text": 'Configuración'},
            {"type": "link", "href": '/docs/empresa.html', "text": 'Datos del negocio'},
            {"type": "link", "href": '/docs/usuarios.html', "text": 'Usuarios y permisos'},
            {"type": "link", "href": '/docs/configuracion.html', "text": 'Configuración general'},
            {"type": "section", "text": 'Salón y Comandas'},
            {"type": "link", "href": '/docs/salon.html', "text": 'Salón y Mesas'},
            {"type": "link", "href": '/docs/comandas-kds.html', "text": 'Comandas y KDS'},
            {"type": "link", "href": '/docs/canales.html', "text": 'Canales sin mesa'},
            {"type": "link", "href": '/docs/recetas.html', "text": 'Recetas y Food Cost'},
            {"type": "section", "text": 'Módulos'},
            {"type": "link", "href": '/docs/ventas.html', "text": 'Ventas'},
            {"type": "link", "href": '/docs/presupuestos.html', "text": 'Presupuestos'},
            {"type": "link", "href": '/docs/clientes.html', "text": 'Clientes'},
            {"type": "link", "href": '/docs/cuenta-corriente.html', "text": 'Cuenta Corriente'},
            {"type": "link", "href": '/docs/caja-turnos.html', "text": 'Caja y Turnos'},
            {"type": "link", "href": '/docs/facturacion.html', "text": 'Facturación electrónica'},
            {"type": "link", "href": '/docs/productos-stock.html', "text": 'Productos y Stock'},
            {"type": "link", "href": '/docs/listas-precio.html', "text": 'Listas de Precios'},
            {"type": "link", "href": '/docs/egresos-proveedores.html', "text": 'Egresos y Proveedores'},
            {"type": "link", "href": '/docs/tesoreria.html', "text": 'Tesorería'},
            {"type": "link", "href": '/docs/depositos.html', "text": 'Depósitos'},
            {"type": "link", "href": '/docs/reportes.html', "text": 'Reportes'},
            {"type": "link", "href": '/docs/libros-iva.html', "text": 'Libros IVA Digital'},
            {"type": "link", "href": '/docs/integraciones.html', "text": 'Integraciones'},
            {"type": "link", "href": '/docs/logs.html', "text": 'Logs de actividad'},
        ],
    },
    'gestiolibra': {
        "brand": 'Gestiolibra',
        "letter": 'G',
        "footer_html": '<footer style="background:var(--dark);color:#94a3b8;text-align:center;padding:1.5rem;font-size:.85rem;">\n  © 2026 Gestiolibra · <a href="/" style="color:#94a3b8">Inicio</a>\n</footer>',
        "sidebar": [
            {"type": "section", "text": 'Inicio'},
            {"type": "link", "href": '/docs/', "text": 'Introducción'},
            {"type": "link", "href": '/docs/primeros-pasos.html', "text": 'Primeros pasos'},
            {"type": "section", "text": 'Configuración'},
            {"type": "link", "href": '/docs/sucursales.html', "text": 'Sucursales y horario'},
            {"type": "link", "href": '/docs/servicios-y-recursos.html', "text": 'Servicios y recursos'},
            {"type": "section", "text": 'Turnos'},
            {"type": "link", "href": '/docs/disponibilidad.html', "text": 'Disponibilidad y bloqueos'},
            {"type": "link", "href": '/docs/agenda-turnos.html', "text": 'Agenda y turnos'},
            {"type": "link", "href": '/docs/clientes.html', "text": 'Clientes'},
            {"type": "section", "text": 'Estándar'},
            {"type": "link", "href": '/docs/recordatorios-senas.html', "text": 'Recordatorios y señas'},
            {"type": "section", "text": 'Premium'},
            {"type": "link", "href": '/docs/facturacion.html', "text": 'Facturación electrónica'},
            {"type": "link", "href": '/docs/caja.html', "text": 'Caja'},
            {"type": "link", "href": '/docs/dashboard.html', "text": 'Dashboard'},
            {"type": "section", "text": 'Cuenta'},
            {"type": "link", "href": '/docs/usuarios-roles.html', "text": 'Usuarios y roles'},
            {"type": "link", "href": '/docs/logs.html', "text": 'Logs del sistema'},
            {"type": "link", "href": '/docs/configuracion.html', "text": 'Configuración'},
        ],
    },
    'medlibra': {
        "brand": 'MedLibra',
        "letter": 'M',
        "footer_html": '<footer style="background:var(--dark);color:#94a3b8;text-align:center;padding:1.5rem;font-size:.85rem;">\n  © 2026 MedLibra · <a href="/" style="color:#94a3b8">Inicio</a>\n</footer>',
        "sidebar": [
            {"type": "section", "text": 'Inicio'},
            {"type": "link", "href": '/docs/', "text": 'Introducción'},
            {"type": "link", "href": '/docs/primeros-pasos.html', "text": 'Primeros pasos'},
            {"type": "section", "text": 'Configuración'},
            {"type": "link", "href": '/docs/profesionales-consultorios.html', "text": 'Profesionales y consultorios'},
            {"type": "link", "href": '/docs/disponibilidad.html', "text": 'Disponibilidad y bloqueos'},
            {"type": "link", "href": '/docs/agenda-turnos.html', "text": 'Agenda y turnos'},
            {"type": "section", "text": 'Dominio clínico (incluido siempre)'},
            {"type": "link", "href": '/docs/pacientes.html', "text": 'Pacientes'},
            {"type": "link", "href": '/docs/historia-clinica.html', "text": 'Historia clínica'},
            {"type": "link", "href": '/docs/recetas.html', "text": 'Recetas'},
            {"type": "link", "href": '/docs/estudios.html', "text": 'Estudios'},
            {"type": "link", "href": '/docs/documentos-clinicos.html', "text": 'Documentos clínicos'},
            {"type": "link", "href": '/docs/consentimientos.html', "text": 'Consentimientos'},
            {"type": "section", "text": 'Estándar'},
            {"type": "link", "href": '/docs/recordatorios-senas.html', "text": 'Recordatorios y señas'},
            {"type": "section", "text": 'Premium'},
            {"type": "link", "href": '/docs/facturacion.html', "text": 'Facturación electrónica'},
            {"type": "link", "href": '/docs/caja.html', "text": 'Caja'},
            {"type": "link", "href": '/docs/dashboard.html', "text": 'Dashboard'},
            {"type": "section", "text": 'Cuenta'},
            {"type": "link", "href": '/docs/usuarios-roles.html', "text": 'Usuarios y roles'},
            {"type": "link", "href": '/docs/logs.html', "text": 'Logs del sistema'},
            {"type": "link", "href": '/docs/configuracion.html', "text": 'Configuración'},
        ],
    },
    'ventalibra': {
        "brand": 'VentaLibra',
        "letter": 'V',
        "footer_html": '<footer style="background:var(--dark);color:#94a3b8;text-align:center;padding:1.5rem;font-size:.85rem;">\n  © 2026 VentaLibra · <a href="/" style="color:#94a3b8">Inicio</a>\n</footer>',
        "sidebar": [
            {"type": "section", "text": 'Inicio'},
            {"type": "link", "href": '/docs/', "text": 'Introducción'},
            {"type": "link", "href": '/docs/primeros-pasos.html', "text": 'Primeros pasos'},
            {"type": "section", "text": 'Catálogo'},
            {"type": "link", "href": '/docs/catalogo.html', "text": 'Catálogo'},
            {"type": "link", "href": '/docs/listas-de-precio.html', "text": 'Listas de precio'},
            {"type": "section", "text": 'Ventas'},
            {"type": "link", "href": '/docs/punto-de-venta.html', "text": 'Punto de venta'},
            {"type": "link", "href": '/docs/stock-inventario.html', "text": 'Stock e inventario'},
            {"type": "section", "text": 'Compras'},
            {"type": "link", "href": '/docs/compras-proveedores.html', "text": 'Compras a proveedores'},
            {"type": "link", "href": '/docs/clientes-proveedores.html', "text": 'Clientes y proveedores'},
            {"type": "link", "href": '/docs/cuenta-corriente.html', "text": 'Cuentas corrientes'},
            {"type": "section", "text": 'Caja y facturación'},
            {"type": "link", "href": '/docs/caja.html', "text": 'Caja'},
            {"type": "link", "href": '/docs/facturacion.html', "text": 'Facturación electrónica'},
            {"type": "section", "text": 'Estándar'},
            {"type": "link", "href": '/docs/reportes.html', "text": 'Reportes'},
            {"type": "section", "text": 'Cuenta'},
            {"type": "link", "href": '/docs/usuarios-roles.html', "text": 'Usuarios y roles'},
            {"type": "link", "href": '/docs/logs.html', "text": 'Logs del sistema'},
            {"type": "link", "href": '/docs/configuracion.html', "text": 'Configuración'},
        ],
    },
    # LibraCargo y LibraClub (2026-08-20). Footer corto, como Contalibra /
    # Gestiolibra / MedLibra / VentaLibra / LibraDesk: el largo de Restolibra
    # repite el footer entero de su landing dentro de cada pagina de /docs/,
    # y en un sitio nuevo no hay nada que preservar.
    'libracargo': {
        "brand": 'LibraCargo',
        "letter": 'C',
        "footer_html": '<footer style="background:var(--dark);color:#94a3b8;text-align:center;padding:1.5rem;font-size:.85rem;">\n  © 2026 LibraCargo · <a href="/" style="color:#94a3b8">Inicio</a>\n</footer>',
        "sidebar": [
            {"type": "section", "text": 'Inicio'},
            {"type": "link", "href": '/docs/', "text": 'Introducción'},
            {"type": "link", "href": '/docs/primeros-pasos.html', "text": 'Primeros pasos'},
            {"type": "section", "text": 'Configuración'},
            {"type": "link", "href": '/docs/empresa.html', "text": 'Datos de la empresa'},
            {"type": "link", "href": '/docs/maestros.html', "text": 'Maestros'},
            {"type": "link", "href": '/docs/arca.html', "text": 'Facturación (ARCA)'},
            {"type": "section", "text": 'Día a día'},
            {"type": "link", "href": '/docs/ordenes.html', "text": 'Órdenes de carga'},
            {"type": "link", "href": '/docs/cuenta-corriente.html', "text": 'Cuenta corriente'},
            {"type": "link", "href": '/docs/caja.html', "text": 'Caja'},
            {"type": "link", "href": '/docs/comprobantes.html', "text": 'Comprobantes'},
            {"type": "section", "text": 'Gestión'},
            {"type": "link", "href": '/docs/tablero.html', "text": 'Tablero'},
            {"type": "link", "href": '/docs/reportes.html', "text": 'Reportes'},
            {"type": "link", "href": '/docs/impresion.html', "text": 'Impresión de listados'},
            {"type": "section", "text": 'Cuenta'},
            {"type": "link", "href": '/docs/usuarios.html', "text": 'Usuarios'},
            {"type": "link", "href": '/docs/logs.html', "text": 'Log de actividad'},
            {"type": "link", "href": '/docs/backup.html', "text": 'Backup y restauración'},
        ],
    },
    'libraclub': {
        "brand": 'LibraClub',
        "letter": 'C',
        "footer_html": '<footer style="background:var(--dark);color:#94a3b8;text-align:center;padding:1.5rem;font-size:.85rem;">\n  © 2026 LibraClub · <a href="/" style="color:#94a3b8">Inicio</a>\n</footer>',
        "sidebar": [
            {"type": "section", "text": 'Inicio'},
            {"type": "link", "href": '/docs/', "text": 'Introducción'},
            {"type": "link", "href": '/docs/primeros-pasos.html', "text": 'Primeros pasos'},
            {"type": "section", "text": 'Configuración'},
            {"type": "link", "href": '/docs/sucursales.html', "text": 'Sucursales'},
            {"type": "link", "href": '/docs/canchas.html', "text": 'Canchas'},
            {"type": "link", "href": '/docs/tarifas.html', "text": 'Tarifas'},
            {"type": "section", "text": 'Día a día'},
            {"type": "link", "href": '/docs/agenda.html', "text": 'Agenda'},
            {"type": "link", "href": '/docs/reservas.html', "text": 'Reservas'},
            {"type": "link", "href": '/docs/canchas-fijas.html', "text": 'Canchas fijas'},
            {"type": "link", "href": '/docs/bloqueos.html', "text": 'Bloqueos'},
            {"type": "link", "href": '/docs/clientes.html', "text": 'Clientes'},
            {"type": "section", "text": 'Cuenta'},
            {"type": "link", "href": '/docs/usuarios.html', "text": 'Usuarios'},
            {"type": "link", "href": '/docs/configuracion.html', "text": 'Configuración'},
            {"type": "link", "href": '/docs/logs.html', "text": 'Log de actividad'},
            {"type": "link", "href": '/docs/backup.html', "text": 'Backup y restauración'},
        ],
    },
}
