"""Metadata (title/description/active_href) por pagina de /docs/,
extraido 2026-07-27 de 82 paginas HTML reales -- ver docs_gen.py.

Desde entonces se sumaron paginas; el total no se fija en ningun lado a
proposito -- ver los guardianes de tests/test_docs_gen.py, que verifican la
coherencia entre este registro, docs_content/ y docs_sidebars.py en vez de
contar."""

PAGES = {
    'contalibra': {
        'caja-turnos.html': {
            "title": 'Caja y Turnos — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/caja-turnos.html',
            "is_index": False,
        },
        'clientes.html': {
            "title": 'Clientes — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/clientes.html',
            "is_index": False,
        },
        'configuracion.html': {
            "title": 'Configuración general — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/configuracion.html',
            "is_index": False,
        },
        'cuenta-corriente.html': {
            "title": 'Cuenta Corriente — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/cuenta-corriente.html',
            "is_index": False,
        },
        'depositos.html': {
            "title": 'Depósitos — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/depositos.html',
            "is_index": False,
        },
        'egresos-proveedores.html': {
            "title": 'Egresos y Proveedores — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/egresos-proveedores.html',
            "is_index": False,
        },
        'empresa.html': {
            "title": 'Datos de la empresa — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/empresa.html',
            "is_index": False,
        },
        'facturacion.html': {
            "title": 'Facturación electrónica — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/facturacion.html',
            "is_index": False,
        },
        'index.html': {
            "title": 'Documentación — Contalibra',
            "description": 'Guías y tutoriales para usar Contalibra: facturación, ventas, caja, stock y más.',
            "active_href": '/docs/',
            "is_index": True,
        },
        'integraciones.html': {
            "title": 'Integraciones — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/integraciones.html',
            "is_index": False,
        },
        'libros-iva.html': {
            "title": 'Libros IVA Digital — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/libros-iva.html',
            "is_index": False,
        },
        'listas-precio.html': {
            "title": 'Listas de Precios — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/listas-precio.html',
            "is_index": False,
        },
        'logs.html': {
            "title": 'Logs de actividad — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/logs.html',
            "is_index": False,
        },
        'presupuestos.html': {
            "title": 'Presupuestos — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/presupuestos.html',
            "is_index": False,
        },
        'primeros-pasos.html': {
            "title": 'Primeros pasos — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/primeros-pasos.html',
            "is_index": False,
        },
        'productos-stock.html': {
            "title": 'Productos y Stock — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/productos-stock.html',
            "is_index": False,
        },
        'reportes.html': {
            "title": 'Reportes — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/reportes.html',
            "is_index": False,
        },
        'tesoreria.html': {
            "title": 'Tesorería — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/tesoreria.html',
            "is_index": False,
        },
        'usuarios.html': {
            "title": 'Usuarios y permisos — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/usuarios.html',
            "is_index": False,
        },
        'ventas.html': {
            "title": 'Ventas — Documentación Contalibra',
            "description": None,
            "active_href": '/docs/ventas.html',
            "is_index": False,
        },
    },
    'restolibra': {
        'caja-turnos.html': {
            "title": 'Caja y Turnos — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/caja-turnos.html',
            "is_index": False,
        },
        'canales.html': {
            "title": 'Canales sin mesa — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/canales.html',
            "is_index": False,
        },
        'clientes.html': {
            "title": 'Clientes — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/clientes.html',
            "is_index": False,
        },
        'comandas-kds.html': {
            "title": 'Comandas y KDS — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/comandas-kds.html',
            "is_index": False,
        },
        'configuracion.html': {
            "title": 'Configuración general — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/configuracion.html',
            "is_index": False,
        },
        'cuenta-corriente.html': {
            "title": 'Cuenta Corriente — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/cuenta-corriente.html',
            "is_index": False,
        },
        'depositos.html': {
            "title": 'Depósitos — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/depositos.html',
            "is_index": False,
        },
        'egresos-proveedores.html': {
            "title": 'Egresos y Proveedores — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/egresos-proveedores.html',
            "is_index": False,
        },
        'empresa.html': {
            "title": 'Datos del negocio — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/empresa.html',
            "is_index": False,
        },
        'facturacion.html': {
            "title": 'Facturación electrónica — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/facturacion.html',
            "is_index": False,
        },
        'index.html': {
            "title": 'Documentación — Restolibra',
            "description": 'Guías y tutoriales para usar Restolibra: mesas, comandas, KDS, facturación, stock y más.',
            "active_href": '/docs/',
            "is_index": True,
        },
        'integraciones.html': {
            "title": 'Integraciones — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/integraciones.html',
            "is_index": False,
        },
        'libros-iva.html': {
            "title": 'Libros IVA Digital — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/libros-iva.html',
            "is_index": False,
        },
        'listas-precio.html': {
            "title": 'Listas de Precios — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/listas-precio.html',
            "is_index": False,
        },
        'logs.html': {
            "title": 'Logs de actividad — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/logs.html',
            "is_index": False,
        },
        'presupuestos.html': {
            "title": 'Presupuestos — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/presupuestos.html',
            "is_index": False,
        },
        'primeros-pasos.html': {
            "title": 'Primeros pasos — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/primeros-pasos.html',
            "is_index": False,
        },
        'productos-stock.html': {
            "title": 'Productos y Stock — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/productos-stock.html',
            "is_index": False,
        },
        'recetas.html': {
            "title": 'Recetas y Food Cost — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/recetas.html',
            "is_index": False,
        },
        'reportes.html': {
            "title": 'Reportes — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/reportes.html',
            "is_index": False,
        },
        'salon.html': {
            "title": 'Salón y Mesas — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/salon.html',
            "is_index": False,
        },
        'tesoreria.html': {
            "title": 'Tesorería — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/tesoreria.html',
            "is_index": False,
        },
        'usuarios.html': {
            "title": 'Usuarios y permisos — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/usuarios.html',
            "is_index": False,
        },
        'ventas.html': {
            "title": 'Ventas — Documentación Restolibra',
            "description": None,
            "active_href": '/docs/ventas.html',
            "is_index": False,
        },
    },
    'gestiolibra': {
        'agenda-turnos.html': {
            "title": 'Agenda y turnos — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/agenda-turnos.html',
            "is_index": False,
        },
        'caja.html': {
            "title": 'Caja — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/caja.html',
            "is_index": False,
        },
        'clientes.html': {
            "title": 'Clientes — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/clientes.html',
            "is_index": False,
        },
        'configuracion.html': {
            "title": 'Configuración — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/configuracion.html',
            "is_index": False,
        },
        'dashboard.html': {
            "title": 'Dashboard — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/dashboard.html',
            "is_index": False,
        },
        'disponibilidad.html': {
            "title": 'Disponibilidad y bloqueos — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/disponibilidad.html',
            "is_index": False,
        },
        'facturacion.html': {
            "title": 'Facturación electrónica — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/facturacion.html',
            "is_index": False,
        },
        'index.html': {
            "title": 'Documentación — Gestiolibra',
            "description": 'Guías para usar Gestiolibra: agenda, turnos, clientes, recordatorios, señas y facturación.',
            "active_href": '/docs/',
            "is_index": True,
        },
        'logs.html': {
            "title": 'Logs del sistema — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/logs.html',
            "is_index": False,
        },
        'primeros-pasos.html': {
            "title": 'Primeros pasos — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/primeros-pasos.html',
            "is_index": False,
        },
        'recordatorios-senas.html': {
            "title": 'Recordatorios y señas — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/recordatorios-senas.html',
            "is_index": False,
        },
        'servicios-y-recursos.html': {
            "title": 'Servicios y recursos — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/servicios-y-recursos.html',
            "is_index": False,
        },
        'sucursales.html': {
            "title": 'Sucursales y horario — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/sucursales.html',
            "is_index": False,
        },
        'usuarios-roles.html': {
            "title": 'Usuarios y roles — Documentación Gestiolibra',
            "description": None,
            "active_href": '/docs/usuarios-roles.html',
            "is_index": False,
        },
    },
    'medlibra': {
        'agenda-turnos.html': {
            "title": 'Agenda y turnos — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/agenda-turnos.html',
            "is_index": False,
        },
        'caja.html': {
            "title": 'Caja — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/caja.html',
            "is_index": False,
        },
        'configuracion.html': {
            "title": 'Configuración — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/configuracion.html',
            "is_index": False,
        },
        'consentimientos.html': {
            "title": 'Consentimientos — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/consentimientos.html',
            "is_index": False,
        },
        'dashboard.html': {
            "title": 'Dashboard — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/dashboard.html',
            "is_index": False,
        },
        'disponibilidad.html': {
            "title": 'Disponibilidad y bloqueos — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/disponibilidad.html',
            "is_index": False,
        },
        'documentos-clinicos.html': {
            "title": 'Documentos clínicos — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/documentos-clinicos.html',
            "is_index": False,
        },
        'estudios.html': {
            "title": 'Estudios — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/estudios.html',
            "is_index": False,
        },
        'facturacion.html': {
            "title": 'Facturación electrónica — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/facturacion.html',
            "is_index": False,
        },
        'historia-clinica.html': {
            "title": 'Historia clínica — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/historia-clinica.html',
            "is_index": False,
        },
        'index.html': {
            "title": 'Documentación — MedLibra',
            "description": 'Guías para usar MedLibra: turnos, pacientes, historia clínica, recetas, estudios, consentimientos y facturación.',
            "active_href": '/docs/',
            "is_index": True,
        },
        'logs.html': {
            "title": 'Logs del sistema — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/logs.html',
            "is_index": False,
        },
        'pacientes.html': {
            "title": 'Pacientes — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/pacientes.html',
            "is_index": False,
        },
        'primeros-pasos.html': {
            "title": 'Primeros pasos — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/primeros-pasos.html',
            "is_index": False,
        },
        'profesionales-consultorios.html': {
            "title": 'Profesionales y consultorios — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/profesionales-consultorios.html',
            "is_index": False,
        },
        'recetas.html': {
            "title": 'Recetas — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/recetas.html',
            "is_index": False,
        },
        'recordatorios-senas.html': {
            "title": 'Recordatorios y señas — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/recordatorios-senas.html',
            "is_index": False,
        },
        'usuarios-roles.html': {
            "title": 'Usuarios y roles — Documentación MedLibra',
            "description": None,
            "active_href": '/docs/usuarios-roles.html',
            "is_index": False,
        },
    },
    'ventalibra': {
        'caja.html': {
            "title": 'Caja — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/caja.html',
            "is_index": False,
        },
        'catalogo.html': {
            "title": 'Catálogo — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/catalogo.html',
            "is_index": False,
        },
        'clientes-proveedores.html': {
            "title": 'Clientes y proveedores — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/clientes-proveedores.html',
            "is_index": False,
        },
        'compras-proveedores.html': {
            "title": 'Compras a proveedores — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/compras-proveedores.html',
            "is_index": False,
        },
        'configuracion.html': {
            "title": 'Configuración — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/configuracion.html',
            "is_index": False,
        },
        'cuenta-corriente.html': {
            "title": 'Cuentas corrientes — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/cuenta-corriente.html',
            "is_index": False,
        },
        'facturacion.html': {
            "title": 'Facturación electrónica — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/facturacion.html',
            "is_index": False,
        },
        'index.html': {
            "title": 'Documentación — VentaLibra',
            "description": 'Guías para usar VentaLibra: catálogo, punto de venta, stock, compras y facturación.',
            "active_href": '/docs/',
            "is_index": True,
        },
        'listas-de-precio.html': {
            "title": 'Listas de precio — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/listas-de-precio.html',
            "is_index": False,
        },
        'logs.html': {
            "title": 'Logs del sistema — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/logs.html',
            "is_index": False,
        },
        'primeros-pasos.html': {
            "title": 'Primeros pasos — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/primeros-pasos.html',
            "is_index": False,
        },
        'punto-de-venta.html': {
            "title": 'Punto de venta — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/punto-de-venta.html',
            "is_index": False,
        },
        'reportes.html': {
            "title": 'Reportes — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/reportes.html',
            "is_index": False,
        },
        'stock-inventario.html': {
            "title": 'Stock e inventario — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/stock-inventario.html',
            "is_index": False,
        },
        'usuarios-roles.html': {
            "title": 'Usuarios y roles — Documentación VentaLibra',
            "description": None,
            "active_href": '/docs/usuarios-roles.html',
            "is_index": False,
        },
    },
}
